# Settings for the app
app:
  # HTML Title
  title: Bluebikes Station Suggestion Map
  # Header name
  name: Bluebikes Station Suggestion Map
  # Meta description that will show up in Google search results
  meta_description: _(Suggest new Bluebikes station locations across the Boston Metro Area. Share your ideas with the community and help improve the Bluebikes network.)
  # Meta author that will show up in Google search results
  meta_author: Poe Public

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  # The default geocoding engine is MapQuest. You can set an override below.
  # Make sure to provide the appropriate keys for whatever you set.
  geocoding_engine: Mapbox
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  # How close is close enough? This is the distance in meters that will be used
  # to determine if a place is close enough to an existing place to be considered
  # "close".
  proximity_radius: 100

  # The minimum zoom level at which the map will show the summary of nearby
  # suggestions. If the zoom level is below this, we will zoom in.
  summary_min_zoom: 14

  mapbox_access_token: pk.eyJ1IjoicG9lcHVibGljIiwiYSI6ImNtYndzbzJxczB1bXoybHM4bGVibDdmZ2oifQ.QRjUod_UlMasyQWf_CjGnQ

  options:
    # Consider including rail lines, bike lanes, and municipal boundaries in
    # the base tiles. If not, will need to load data separately.
    style: mapbox://styles/poepublic/cmcqmiic400lb01qvgtpj458g
    center:
      - -71.06753869851728
      - 42.35383902647486
    zoom: 12.5
    minZoom: 10
    maxZoom: 16
    scrollWheelZoom: false
  layers:
    # Raster Tile Layers
    # ==================
    # - url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
    #   attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'

    # Mapbox GL Layers
    # ================
    - type: mapbox
      style: mapbox://styles/mapbox/streets-v8
      accessToken: pk.eyJ1Ijoib3BlbnBsYW5zIiwiYSI6ImZRQzRPYnMifQ.f75KI3Q9rFXRY2Zciz6DKw
      fallback:
        url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'

    # GeoJSON Layers
    # ==============
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#444"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  suggestion:
    label: _(Suggestion)
    rules:
      - condition: '{{map.zoom}} < 20 && {{layer.focused}} === false'
        # Display suggestions as circles (vectors) when zoomed out

        style:
          color: '#0d85e9'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: false
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  editors: place-editors
  moderators: place-editors
  response_name: _(suggestion)
  response_plural_name: _(suggestions)
  add_button_label: _(Suggest a station location)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Suggestions)
  show_map_button_label: _(Show the Map)
  action_text: _(submitted)
  title: _(Bikeshare Suggestions)
  help_text: _(Suggestions do not guarantee a station; rather, suggestions are helpful feedback to augment existing processes that determine where and when new stations are added or expanded.)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location
  location_type: suggestion

  items:
    - prompt: _(Location Type)
      type: hidden
      name: location_type
    - prompt: _(This is a good location because it is...)
      type: checkboxgroup
      name: good_location_reasons
      required: true
      attrs:
        - key: data-group-required
        - key: data-has-children
        - key: data-custom-validity
          value: _(Please select at least one reason why this is a good location.)
      options:
        - label: _(Close to work/school)
          value: work_or_school
          color: '#a6cee3'
        - label: _(Close to home/family/friends)
          value: home
          color: '#1f78b4'
        - label: _(Close to rail, T, or bus station)
          value: transit
          color: '#b2df8a'
        - label: _(Close to errands)
          value: errands
          color: '#33a02c'
        - label: _(Close to leisure activities)
          value: leisure
          color: '#fb9a99'
        - label: _(Something else)
          value: other
          color: '#e31a1c'
    - prompt: _(Please let us know why this would be a good station location.)
      type: text
      name: good_location_other_reason
      required: true
      attrs:
        - key: required
        - key: data-parent-field
          value: good_location_reasons
        - key: data-parent-value
          value: other
    - prompt: _(Seems like there's already a station nearby; why would an additional or bigger station here be useful?)
      type: checkboxgroup
      name: another_station_reasons
      required: true
      attrs:
        - key: data-group-required
        - key: data-has-children
        - key: data-custom-validity
          value: _(Please select at least one reason why you think another station is needed.)
        - key: data-show-when-close-to-station
      options:
        - label: _(The existing station is often too full/empty)
          value: capacity
        - label: _(A new/different location would improve accessibility)
          value: accessibility
        - label: _(Something else)
          value: other
    - prompt: _(Please let us know why another station is needed.)
      type: text
      name: another_station_other_reason
      required: true
      attrs:
        - key: required
        - key: data-parent-field
          value: another_station_reasons
        - key: data-parent-value
          value: other

pages:
  - title: _(About this map)
    slug: about
    name: overview
    start_page: true
  
  - title: _(How it works)
    external: true
    url: https://bluebikes.com/how-it-works
  
  - title: _(Pricing)
    external: true
    url: https://bluebikes.com/pricing
  
  - title: _(System map)
    external: true
    url: https://account.bluebikes.com/map
  
  - title: _(Explore Metro Boston)
    external: true
    url: https://bluebikes.com/explore-metro-boston

  - title: _(Income Eligible)
    external: true
    url: https://bluebikes.com/pricing/income-eligible-program
  
  - title: _(Help)
    external: true
    url: https://help.bluebikes.com/hc/en-us



notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
